# ************************************************************
# Sequel Pro SQL dump
# Version 3408
#
# http://www.sequelpro.com/
# http://code.google.com/p/sequel-pro/
#
# Host: 127.0.0.1 (MySQL 5.5.9)
# Database: crafty_hops22
# Generation Time: 2012-12-07 01:54:10 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table Beers
# ------------------------------------------------------------

DROP TABLE IF EXISTS `Beers`;

CREATE TABLE `Beers` (
  `beer_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `beerName` varchar(50) DEFAULT NULL,
  `abv` varchar(20) DEFAULT NULL,
  `image` varchar(200) DEFAULT NULL,
  `decription` text,
  `brewedBy` varchar(200) DEFAULT NULL,
  `location` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`beer_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

LOCK TABLES `Beers` WRITE;
/*!40000 ALTER TABLE `Beers` DISABLE KEYS */;

INSERT INTO `Beers` (`beer_id`, `beerName`, `abv`, `image`, `decription`, `brewedBy`, `location`)
VALUES
	(1,'Fat Tire','5.20%',NULL,'Named in honor of our co-founder\'s bike trip through Europe, Fat Tire Amber Ale marks a turning point in the young electrical engineer\'s home brewing. Belgian beers use a far broader palette of ingredients (fruits, spices, esoteric yeast strains) than German or English styles. Together with co-founder, Kim Jordan, they traveled around sampling their homebrews to the public. Fat Tire won fans with its sense of balance: toasty, biscuit-like malt flavors coasting in equilibrium with hoppy freshness.','New Belgium Brewing','Fort Collins, Colorado'),
	(2,'Rogue Santas Private Reserve','6.00%',NULL,'Rogue\'s annual holiday offering, Santa\'s Private Reserve, is a variation of the classic Saint Rogue Red, but with double the hops--including Chinook, and Centennial, and a mystery hop called Rudolph by head brewer John \"more hops\" Maier! This holiday elixir is brewed with two-row Harrington, Klages and Munich malts, along with Hugh Baird 30-37, Carastan 13-17, and Crystal 70-80 malts, plus free range coastal water and proprietary top-fermenting Pacman yeast.','Rogue Ales','Newport, Oregon'),
	(3,'Tröegs HopBack Amber Ale','6.00%',NULL,'Squeeze those hops for all they?re worth and prepare to pucker up: Tröegs? newest single batch brew, Nugget Nectar Ale, will take hopheads to nirvana with a heady collection of Nugget, Warrior and Tomahawk hops. Starting with the same base ingredients of our flagship HopBack Amber Ale, Nugget Nectar intensifies the malt and hop flavors to create an explosive hop experience.','Tröegs Brewing Company','Hershey, Pennsylvania'),
	(4,'Levitation Ale','4.40%',NULL,'This deep amber ale has rich & roasty malt flavors, a big hoppy character, citrus overtones (courtesy of the hops and our special brewers yeast) and modest alcohol.','Stone Brewing Co.','Escondido, California'),
	(5,'Bear Republic Red Rocket Ale','6.80%',NULL,'Red Rocket Ale is a bastardized Scottish style red ale that traces it?s origins to our homebrew roots. This full bodied and hoppy brew finishes on the palate with sweet, caramel malt flavors. 2009 California State Fair - SILVER 1999 Great American Beer Festival® Other Strong Ales or Lagers - SILVER 1998 Great American Beer Festival® Other Strong Ales - SILVER','Bear Republic Brewing Company','Healdsburg, California'),
	(6,'Red Seal Ale','5.40%',NULL,'Malt and hops are beautifully married in this full-bodied, copper-red Pale Ale. Red Seal is generously hopped for a long, spicy finish. An excellent accompaniment to grilled meats and rich sauces','North Coast Brewing Co.','Fort Bragg, California'),
	(7,'Bell\'s Amber Ale','5.80%',NULL,'Made from mostly pale malt and some Munich and caramel malts. These add a little sweetness, which is balanced by more hops. The result is a rich color and fruity flavor.','Bell\'s Brewery','Kalamazoo, Michigan'),
	(8,'Budweiser American Ale','5.30%',NULL,'Carefully brewed with barley from America?s heartland and cascade hops from the pacific northwest, this rich, amber colored ale has robust flavor and a distinctive hoppy finish.','Anheuser-Busch InBev','St. Louis, Missouri'),
	(9,'Lagunitas Censored ','6.75%',NULL,'This ale contains no actual copper but we?re pretty literal... It looked coppery, so we lamely called it a copper ale. Lots?a nice caramel malt though. Originally 5.9% alcohol by volume.','Lagunitas Brewing Company','Petaluma, California'),
	(10,'Green Flash Hop Head Red','7.00%',NULL,'Resinous hop characteristics emerge from an enormous hopping with Columbus, Nugget and Amarillo overtaking the rich caramel malt base. To add luscious hop flavors and enticingly floral hop aromas, we dry-hop the brew with bucket loads of Amarillo hops. Welcome to the world of Red IPA.','Green Flash Brewing Co.','San Diego, California'),
	(11,'Twisted Pine American Amber Ale','5.50%',NULL,'This American Amber Ale is a medium bodied beer with good hop character. The aroma is moderately hoppy, moderately malty, and lightly yeasty. The beer?s texture starts off crisp and effervescent, and becomes a little thicker and perhaps even chewier toward the finish. Goes great with a barbecued burger, which brings out some of the beer?s woodsy and earthy notes. ','Twisted Pine Brewing','Boulder, Colorado'),
	(12,'Boont Amber Ale','5.80%',NULL,'A medium bodied pale ale with a beautiful copper color, a robust head, and the rich flavor of caramel malt.','Anderson Valley Brewing Company','Boonville, California'),
	(13,'Highland Gaelic Ale','5.80%',NULL,'A deep amber colored American ale, featuring a rich malty body. Cascade and Willamette hops add a complex hop flavor and aroma. This ale is exceptionally balanced between malty sweetness and delicate hop bitterness.','Highland Brewing Company','Asheville, North Carolina'),
	(14,'Mendocino Red Tail Ale','6.10%',NULL,'Red Tail Ale - The Legend is our flagship brand. It is brewed in the traditional \"old world\" manner, using premium two-row malted barley, hops and our own special proprietary yeast strain. It is an amber ale with a rich complex refreshing flavor and a crisp dry finish. Red Tail Ale is \"Bottle Conditioned.\" Like good wine, Red Tail Ale is a perfect complement to fine dining.','Mendocino Brewing Company','Hopland, California'),
	(15,'Avalanche Ale','5.41%',NULL,'Subtlety. That\'s what makes our Avalanche amber ale such a treat. We blend pale and caramel malts and just a kiss of bittering hops to create a refreshing, but flavorful, any time beer. Aromas of pale grains, a semi-sweet middle and a clean as Colorado snow finish make this our best-selling beer.','Breckenridge Brewery','Denver, Colorado'),
	(16,'Full Sail Amber','5.50%',NULL,'The best selling Amber in the Northwest. It?s a great tasting malty sweet beer that has rich amber hue, a full body, and a spicy floral hop finish. This American style amber ale is brewed with: 2 row Pale, Crystal and Chocolate malts and is hopped with Mt. Hood and Cascade hops.','Full Sail Brewing Company','Hood River, Oregon'),
	(17,'Captain Sig\'s Northwestern Ale','6.20%',NULL,'Originally a tweak of Eugene City Tracktown 100 Meter Ale, reformulated for release as Captain Sig?s Deadliest Ale.','Rogue Ales','Newport, Oregon'),
	(18,'Calico Copper Amber Ale','5.00%',NULL,'Calico Amber Ale is brewed in the American Amber style. Full bodied and aromatic, it is brewed with 6 malts for deep red color and full flavor.','Ballast Point Brewing Company','San Diego, California'),
	(19,'Hex','5.40%',NULL,'Hex is a malty amber ale offering hints of toffee and caramel with its slightly smoky finish. Malt: Pale, Vienna, Crystal, Cherry Wood Smoked Malt, Rye Hops: Hallertau Yeast: German Ale Yeast.','Magic Hat Brewing Company','South Burlington, Vermont'),
	(20,'He\'Brew Genesis Ale','6.00%',NULL,'Contract brewed for Shmaltz Brewing Company. The First Creation. Crisp, smooth and perfectly balanced between a west coast style pale and amber ale, with a supple malt sweetness and a pronounced hop flourish. ','Shmaltz Brewing Company','Brooklyn, New York'),
	(21,'Autumn Fest','5.40%',NULL,'AutumnFest is Weyerbachers own unique twist on the German Oktoberfest style. Copper-amber in color, AutumnFest is made with Vienna and Munich malts for that authentic, Bavarian easy drinking taste. Each sip imparts a wonderful roastiness of malt on the tongue followed by a smooth, consistent finish. AutumnFest is generally available in stores August through December.','Weyerbacher Brewing Co.','Easton, Pennsylvania'),
	(22,'Prohibition Ale','6.10%',NULL,'Prohibition Ale is a boldly hopped amber ale that strikes a perfect balance between caramel maltiness and it\'s aggressive hopping.','Speakeasy Ales and Lagers','San Francisco, California'),
	(23,'Shark Attack Double Red Ale','9.50%',NULL,'This is a classic West Coast-style imperial red ale brewed with medium crystal malts, centennial and cascade hops. The color is a burnt amber with red highlights and the aroma has a spicy hop presence with moderate caramel malt accents. The taste is a smooth, malty one with a balanced hoppy finish that includes hints of sweet caramel.','Port Brewing/Lost Abbey','San Marcos, California'),
	(24,'YuleSmith (Winter)','9.50%',NULL,'For the winter season, YuleSmith is brewed as an Imperial Red Ale. This version is maltier, more balanced, and darker in color than the summer version. Although quite malty, big hop flavors and aromas are abundant making this an unforgettable winter warmer. Winter YuleSmith is packaged in traditional holiday red and green.','AleSmith Brewing Company','San Diego, California'),
	(25,'5 A.M. Saint','5.00%',NULL,'5am Saint is The Holy Grail of red ales. We live in a world of disposable deities. Someone, somehow has managed to press that big, flashing moronic override button and we?re hard wired straight into the pockets of false idols trying to make a quick buck. Sadly, for a lot of people the same mentality applies to beer. But who?s to know what?s worth worshiping when monolithic advertising budgets have you sucked down the rabbit hole in the blink of an eye? At BrewDog we are on a mission to open as many people?s eyes as possible. Cast away any aspersions and let the crook of BrewDog be your guide in a whirlwind of conformity and mediocrity. Once this ruby liquid forms a foamy halo around your glass, you?ll never want to look back.','BrewDog','Fraserburgh, Aberdeenshire, Scotland'),
	(26,'Red Stripe Jamaican Lager','4.70%',NULL,'First brewed in 1938. It is a light alcohol drink with not too strong bitterness but rather soft taste; therefore, it\'s easy to drink it up.','Desnoes and Geddes (Diageo PLC)','Kingston, Jamaica'),
	(27,'Rolling Rock Extra Pale','4.50%',NULL,'From the glass lined tanks of Old Latrobe we tender this premium beer for your enjoyment, as a tribute to your good taste. It comes from the mountain springs to you.','Anheuser-Busch InBev','St. Louis, Missouri'),
	(28,'Labatt Blue','5.00%',NULL,'Fruity character with slightly sweet aftertaste. Light, crisp and delicate in its flavour delivery.','Labatt Breweries (InBev)','London, Canada'),
	(29,'Dos Equis XX Special Lager','4.45%',NULL,'Dos Equis Special Lager is a refreshing, crisp, golden, lager style beer imported from Mexico. Made with roasted malts, choice hops, a unique strain of yeast and purified water, this distinctive brew is known simply as ?Lager? in its homeland.','FEMSA - Cuauhtémoc-Moctezuma (Heineken)','Monterrey/Veracruz-Llave, Mexico'),
	(30,'Tecate','4.55%',NULL,'A Lager beer with a delicious aroma of malt and hops and a delicate balance in its subtle refreshing taste.','FEMSA - Cuauhtémoc-Moctezuma (Heineken)','Monterrey/Veracruz-Llave, Mexico'),
	(31,'Modelo Especial','4.40%',NULL,'Modelo Especial, a pilsener type beer, was introduced to the market in 1966. Today it is sold in glass bottles as well as cans, which are having an increasing demand due to consumer preferences, making Modelo Especial the leader in the can segment in Mexico.','Grupo Modelo (Corona)','México DF, Mexico'),
	(32,'Molson Canadian Lager','5.00%',NULL,'Using crystal clear water, the finest hops and Canadian grown malted barley, Molson slowly ferments each brew to produce a smooth, refreshing beer with genuine Canadian taste.','Molson Breweries (MolsonCoors)','Montreal, Canada'),
	(33,'Pacifico','4.50%',NULL,'Pacifico, a pilsener type beer, dates back to the beginning of 1900?s. Since 1985, Pacífico has been exported mainly to the West Coast of USA, where it has gained strong recognition.','Grupo Modelo (Corona)','México DF, Mexico'),
	(34,'Landshark Lager','4.70%',NULL,'Brewed in Jacksonville for Margaritaville Brewing Co. Refreshing, drinkable island lager. Found in 4.7% and 4.0% variants.','Anheuser-Busch InBev','St. Louis, Missouri'),
	(35,'Schlitz','4.70%',NULL,'Schlitz?s formula recalls the original hearty taste of the classic 1960?s Schlitz a true Pilsner, perfectly balanced between full-flavor and easy drinking, with just \"a kiss of the hops.\" So, if you want to experience the gusto again, crack open a cold classic, and taste the world?s second best selling beer of the 1960?s.','Miller Brewing Company (MillerCoors)','Woodridge, Illinois'),
	(36,'Tusker Premium Lager','5.00%',NULL,'A clean, refreshing lager capable of subduing any thirst.','Kenya Breweries (East African Breweries - Diageo)','Nairobi, Kenya'),
	(37,'Narragansett Lager','5.50%',NULL,'This traditional German Oktoberfest style beer is brewed with the highest quality German malt & hops. Available during the fall season on tap and in 16oz Cans. The Fest is crafted in small batches at Cottrell Brewery in Pawcatuck, CT and at the award-winning High Falls Brewery in Rochester, NY under the supervision of Brew-master Sean Larkin. Vienna, Pilsner, Light and Dark Munich malts make up the backbone of this beast, and Northern Brewer & Tettnanger hops are added to give it a crisp but subtle hop flavor.','Cottrell Brewing Company','Providence, Rhode Island'),
	(38,'Taj Mahal Premium Lager','4.50%',NULL,'A clean, crisp, pleasant beer. Light and delicate flavor.','United Breweries Group','Bangalore, India'),
	(39,'Simpler Times Lager','6.20%',NULL,'There are times when an ice cold beer fits the bill. This is an easy drinking brew that?s reliably tasty without being fussy. It?s a straightforward beer with good hop flavor without it being over the top. This speaks of a simpler time when you could order a beer, and they wouldn?t bring you a full menu. They?d just bring a good beer at a good price. Life can be complicated, but your beer does not have to be. Enjoy the taste of Simpler Times.','Minhas Craft Brewery','Monroe, Wisconsin'),
	(40,'Leinenkugel\'s Original','4.50%',NULL,'Has a distinctive, crisp, full flavor, that goes down smooth.','Leinenkugel Brewing Company (Tenth & Blake Beer Co.)','Chippewa Falls, Wisconsin'),
	(41,'Sierra Nevada Pale Ale','5.60%',NULL,'Sierra Nevada Pale Ale is a delightful example of the classic pale ale style. It has a deep amber color and a exceptionally full-bodied, complex character. The fragrant bouquet and spicy flavor are the results of the generous use of the best Cascade hops.','Sierra Nevada Brewing Company','Chico, California'),
	(42,'Sierra Nevada Tumbler Autumn Brown','5.50%',NULL,'Sierra Nevada uses malt within days of roasting at the peak of its flavor to give Tumbler a gracefully smooth malt character. 2 row pale, crystal 40, chocolate and smoked malts give it a malty complexity. Challenger hops in the boil add balancing bitterness, while more Challengers and some Goldings give just enough hop flavor in the finish to balance all that malt.','Sierra Nevada Brewing Company','Chico, California'),
	(43,'Sierra Nevada Celebration Ale','6.80%',NULL,'Sierra Nevada Celebration Ale represents a time honored tradition of brewing a special beer for the holiday season. There are generous portions of barley malts and fine whole hops of several varieties, creating a brew with a full, rich and hearty character.','Sierra Nevada Brewing Company','Chico, California'),
	(44,'Sierra Nevada Summerfest','5.00%',NULL,'Summerfest is a delightfully refreshing example of a traditional style lager beer. While lighter in body than our ales, Summerfest displays significant hop aroma and a tangy hop bite. The long lagering period adds a smoothness that makes this beer a great summertime treat.','Sierra Nevada Brewing Company','Chico, California'),
	(45,'Allagash Curieux','11.00%',NULL,'Allagash Curieux is a unique beer that was aged for 8 weeks in Jim Beam Bourbon Barrels. In July 2004 they brewed a batch of the Triple and placed it in Bourbon barrels from Kentucky.','Allagash Brewing Company','Portland, Maine'),
	(46,'Braumeister Selekt Imperial Pilsner Brau (IPB)','6.50%',NULL,'This is an intensely hopped, robust, Pilsener that emphasizes the noble hops from central Europe including Hallertau, Tettnang, Spalt and Saaz. It has been brewed in accordance with the German Purity Law of 1516. IPB is naturally carbonated and unfiltered.','Gordon Biersch Brewing Company','San Jose, California'),
	(47,'Bam Biere','4.50%',NULL,'This delicious farmhouse ale is named for our Jack Russell, who struck by a car, bounced back in fine tenacious Jack Russell fashion, and is brewed for those of us who knocked down, have picked up, dusted off and carried on undaunted. Golden, naturally cloudy, bottle conditioned and dry hopped for a perfectly refreshing balance of spicy malts, hops and yeast. Please enjoy our beers in good health, And look both ways when crossing the street!','Jolly Pumpkin Artisan Ales','Dexter, Michigan'),
	(48,'Bam Noire','4.30%',NULL,'One of Bam\'s brown eyes is, in fact, black. When mischief reigns supreme, it positively glows. Dedicated to the dark side; smooth, dark, incredibly delicious as only a Jack Russell with bat wings can be.','Jolly Pumpkin Artisan Ales','Dexter, Michigan'),
	(49,'Weizen Bam','4.50%',NULL,'The fourth in our Bam Farmhouse series, and perhaps our most adventurous; a traditional farmhouse style hefeweizen. Weizen Bam seamlessly blends traditional German style hefeweizen yeast with our own local wild and sour cultures, for a melange of the most flavorful sort. Ruddy golden, with yeast driven esters of banana, spicy clove, and nutmeg all wrapped up with a generous dose of good-natured rapscallion delight.','Jolly Pumpkin Artisan Ales','Dexter, Michigan'),
	(50,'Old Foghorn Ale','8.80%',NULL,'This barleywine-style ale, the first of its kind in modern times in the United States, has a luscious depth of flavour that makes it ideal for sipping after dinner. It is made with top-fermenting yeast, fresh whole hops, and \"first wort\", the richest runnings of a thick all-malt mash. Old Foghorn is \"dry hopped\" in the classic ale tradition and aged in our cellars until it attains the perfect balance of malty sweetness, estery fruitiness, and exquisite hop character, for which it is known throughout the world. A ruby red ale with little carbonation and a warm finish.','Anchor Brewing Company','San Francisco, California'),
	(51,'Small Beer','3.30%',NULL,'The tradition of brewing two distinct beers from one mash has existed for thousands of years, and for centuries the term \"small beer\" was used in English to describe the lighter and weaker second beer. We make our Old Foghorn Barleywine Style Ale from the rich first runnings of an all-malt mash, and Anchor Small Beer is our attempt to duplicate the \"small beers\" of old by sparging that same mash: sprinkling warm water over the Old Foghorn mash after the first wort has run off, thereby creating a second, lighter brew from the resulting thinner wort. We believe you will find Anchor Small Beer delicious similar to what modern brewers call a \"bitter\" and we hope you will also enjoy the idea of reviving an ancient brewing tradition, which is something of great importance.','Anchor Brewing Company','San Francisco, California'),
	(52,'Orval','6.20%',NULL,'In contrast to all the others, the Orval Trappist brewery makes only one beer for the general public. It has an intensely aromatic and dry character. Between the first and second fermentations there is also an additional dry-hopping process. Through this the beer acquires its pronounced hoppy aroma and extra dry taste.','Brasserie dOrval','Florenville - Villers-d.-Orval, Belgium'),
	(53,'1648 Bee-Head','4.60%',NULL,'Seasonal - May to September. Honey coloured ale gently flavoured with pure Sussex Honey but balanced with a gentle biscuit edge. The biscuit edge prevents the honey from becoming too overpoweringly sweet.','1648','Lewes, England'),
	(54,'Saison Dupont Vieille Provision','6.50%',NULL,'Saison Dupont is a classic Belgian farmhouse ale. This is a beautifully balanced, complex beer that has a refreshing fruitiness and long, dry finish. It is bottled unfiltered so it may be cloudy or have a slight sediment but this is normal and perfectly natural.','Brasserie Dupont','Tourpes-Leuze, Belgium'),
	(55,'Saison Dupont Dry Hopping','6.50%',NULL,'Yearly limited release - 250 kegs, 500 numbered bottles - initially only for the home market but now available for general release in supermarkets, with 2011 date. 30 kegs were unfiltered.','Brasserie Dupont','Tourpes-Leuze, Belgium'),
	(56,'Schneider Weisse Original','5.40%',NULL,'With its amber mahogany coloring and streaked with fine top fermented yeast, this beer has a fine, persistent head that adheres well to the glass. It is pleasantly fruity with a typical top fermented smell, an aroma of clove and nutmeg apple tantalizes the nose. On the tongue it is fresh, clean, full bodied, harmonious and well balanced. It finishes with a light, delicate taste of bitters leaving behind a sour impression.','Weissbierbrauerei G. Schneider & Sohn','Kelheim, Germany'),
	(57,'Three Floyds Dark Lord','15.00%',NULL,'A Demonic Imperial Russian stout brewed with INTELLIGENTSIA coffee,vanilla, and molasses. DarkLord is only available once a year at DarkLord Day at the Three Floyds Brewpub.\nVintage guide:\n\nRed wax = 2004\nOrange wax = 2005\nGold wax = 2006\nSilver wax = 2007\nBlack wax = 2008\nWhite wax = 2009\nGreen wax = 2010 - 15% ABV\nYellow wax = 2011 - 15% ABV\nRed wax = 2012 - 15% ABV','Three Floyds Brewing Company','Munster, Indiana'),
	(58,'Bare Hands Apollo Double IPA','12.00%',NULL,'A huge Double IPA brewed with American 2 row barley and Apollo hops. The majority of bitterness comes from late kettle additions of this news super alpha hop variety. A delicate balance of bitterness, hop flavor, and malt sweetness makes this ale a smooth sipper.','Bare Hands Brewery','Granger, Indiana'),
	(59,'Hoptopus Double','8.80%',NULL,'Hoptopus IPA is an 8-legged hophead?s dream. Its 8.8% ABV malt base balances with 8 separate additions of hops, 88 IBUs, and a foolishly generous dry hop to make this denizen of the deep a lupulin delight.','Beach Brewing Company','Virginia Beach, Virginia'),
	(60,'Crooked Line Detour Double India Pale Ale','9.50%',NULL,'Detour blazes the trail for fresh and bold Double IPAs. Four varieties of hops combine to step up the flavor profile. A hoppy adventure that finishes dry. Big in alcohol and character. Venture to pair with other spirited flavors such as those found in spicy ethnic foods.','Uinta Brewing Company','Salt Lake City, Utah'),
	(61,'Aprihop','7.00%',NULL,'A strong IPA brewed with real apricots and finished with whole leaf Willamette and Cascade hops.','Dogfish Head Brewery','Milton, Delaware'),
	(62,'Black and Blue','10.00%',NULL,'Black & Blue is golden Belgian Ale made with over 300 lbs of fresh blackberries and blueberries. With a deep purple full body and a long-lasting lacy pink head, this ale is both attractive and delicious! It is tart and fruity, like our brewers! The subtle bitterness of Hallertau and Saaz hops shines through the fruit forward flavor and sets the palate aglow. This tasty brew has smooth but noticeable alcohol warmth. Belgian yeast gives this brew a characteristically dry spicy finish. The beautiful interplay of fruit, spice, and alcohol is complimented by a soft malt profile, and a high level of carbonation.','Dogfish Head Brewery','Milton, Delaware'),
	(63,'Black and Red','10.50%',NULL,'Black & Red is a velvety smooth dry-minted stout with a serious fruit problem! The huge portion of heavily roasted grains brings a dry, chocolaty character which contrasts its sweet fruity full body. As you tilt your glass, youll notice that the black color you are perceiving is actually a very deep reddish hue and the rich creamy foam has a tinge of pink to it. Black & Red starts off roasted and warming with a robust mintiness from 100lbs of organic mint (from Washington?s Green Grocer) added to the secondary fermentation and finishes out sweet and smooth.','Dogfish Head Brewery','Milton, Delaware'),
	(64,'Black Hole IPA','8.50%',NULL,'Black Hole derives its name from the color and style of their brew, along with single hop variety employed ? Galaxy.  The color of this otherworldly IPA is as black as the outer reaches of space, with an intense flavor of fresh cut grass and pungent citrus rind.  If you like hops, this one?s for you.  Despite the IBU?s on this intense ale, a dark chocolate and sweet espresso maltiness balances the extreme hoppiness with a smooth creamy finish.','Dogfish Head Brewery','Milton, Delaware'),
	(65,'Sam Adams Alpine Spring','5.50%',NULL,'Samuel Adams Alpine Spring is yet another addition to the brewery?s Small Batch series. For this entry, Sammy & Co used the more traditional labeling. Starting in late October, you?ll see the first of the Small Batch hit the market ? Tasman Red, Third Voyage, Griffin?s Bow, The Vixen. This unfiltered lager is perfect for spring. Noble Tettnang hops, grown in the foothills of the Alps, give the brew a bright citrus and floral aroma flavor. These are balanced by the slightly sweet crisp notes of 2 row pale and honey malts.','Boston Beer Company','Boston, Massachusetts'),
	(66,'Samuel Adams Boston Lager','4.80%',NULL,'Samuel Adams Boston Lager® is the best example of the fundamental characteristics of a great beer, offering a full, rich flavor that is both balanced and complex. It is brewed using a decoction mash, a time consuming, traditional four vessel brewing process discarded by many contemporary brewers. This process brings forth a rich sweetness from the malt that makes it well worth the effort. Samuel Adams Boston Lager® also uses only the finest of ingredients including 2 row barley, as well as German Noble aroma hops. The exclusive use of two row barley not only imparts a full, smooth body but also gives the beer a wide spectrum of malt flavor ranging from slightly sweet to caramel to slightly roasted.','Boston Beer Company','Boston, Massachusetts'),
	(67,'Samuel Adams Octoberfest','5.30%',NULL,'The first thing you notice when pouring a glass of this seasonal beer is the color. Samuel Adams® Octoberfest has a rich, deep golden amber hue which itself is reflective of the season. Samuel Adams® Octoberfest is a malt lover?s dream, masterfully blending together four roasts of barley to create a delicious harmony of sweet flavors including caramel and toffee. The beer is kept from being overly sweet by the elegant bitterness imparted by the German Noble hops. Samuel Adams® Octoberfest provides a wonderful transition from the lighter beers of summer to the winter?s heartier brews. ','Boston Beer Company','Boston, Massachusetts'),
	(68,'Samuel Adams Winter Lager','5.60%',NULL,'Bold and rich, with a touch of holiday spice. The first thing one notices about a Samuel Adams® Winter Lager is the deep ruby color. Then comes the magical aroma which promises something special on the tongue. The cinnamon, ginger, and hint of citrus from the orange peel blend with the roasty sweetness of the malts to deliver a warming, spicy flavor. On the palate Samuel Adams Winter Lager is rich and full bodied, robust and warming, a wonderful way to enjoy the cold evenings that come with the season.','Boston Beer Company','Boston, Massachusetts'),
	(69,'Smuttynose Smuttonator','9.60%',NULL,'S\'muttonator is a tasty mixture of German ingredients and good ol\' fashioned New England tenaciousness. Our brewers take 30 hours to brew a single batch of this traditional Double Bock. Take your time and enjoy its rich, malty, and deceptively smooth flavor.','Smuttynose Brewing Company','Portsmouth, New Hampshire'),
	(70,'Smuttynose Robust Porter','5.70%',NULL,'A hearty ebony colored ale that starts with a rich malty palate finished with clean hops and notes of coffee and chocolate.','Smuttynose Brewing Company','Portsmouth, New Hampshire'),
	(71,'Smuttynose Old Brown Dog','5.70%',NULL,'Old Brown Dog has been cited as a classic example of the \"American Brown Ale\" style of beer. Compared to a typical English Brown Ale, Old Brown Dog is fuller-bodied and more strongly hopped.','Smuttynose Brewing Company','Portsmouth, New Hampshire'),
	(72,'Smuttynose Maibock','7.70%',NULL,'Maibocks are a traditional Teutonic seasonal specialty. We brew ours to be hugely malty and subtly finished with a variety of continental hops, with an eye-pleasing russet brown color.','Smuttynose Brewing Company','Portsmouth, New Hampshire'),
	(73,'Smuttynose IPA','6.60%',NULL,'Smuttynose IPA is a physical salute to the glory of the American hop grower. The citrusy hop flavor coming from a mixture of Simcoe and Santiams is pleasantly balanced by a smooth bitterness from the Amarillo hops. The beer itself is light bodied and crisp with a golden color that will throw a slight haze, as we bottle it unfiltered. At 65 IBU\'s, this is definitely not a training-wheels IPA, but is meant for hop lovers looking to satisfy their craving in a way that\'s not easy to find. We think they?ll be quite pleased.','Smuttynose Brewing Company','Portsmouth, New Hampshire'),
	(74,'Smuttynose Summer Weizen Ale','5.20%',NULL,'Light, tasty & full of character, the summer wheat ale is brewed with a combination of domestic and continental wheat and barley malts, lightly hopped & fermented with a Belgian wit yeast, resulting in a delightfully tangy & refreshing flavor. This beer is brewed for warm weather enjoyment.','Smuttynose Brewing Company','Portsmouth, New Hampshire'),
	(75,'Smuttynose Homunculus','9.00%',NULL,'The base beer is a Belgian triple brewed with White Labs Chimay-style yeast. The hopping was done with Vanguard, Sterling and East Kent Goldings.','Smuttynose Brewing Company','Portsmouth, New Hampshire'),
	(76,'Smuttynose Gravitation','10.00%',NULL,'Gravitation Belgian Quad is the newest offering in the Smuttynose Big Beer Series. This strong dark ale is brewed using a variety of Belgian specialty malts along with 200 pounds of raisin puree per batch. The resulting flavor is a viscous mix of dark fruit, rum, toffee and raisins balanced with aromatic fruitiness of the Belgian yeast.','Smuttynose Brewing Company','Portsmouth, New Hampshire'),
	(77,'Smuttynose Winter Ale','5.83%',NULL,'Smuttynose Winter Ale is a full-bodied, amber beer brewed with a special Trappist ale yeast. Stylistically reminiscent of a Belgian Abbey Double, it features fruity aromas and flavor, balanced by soft Crystal hops. Warming, mellow & pleasantly complex, Smuttynose Winter Ale is your perfect cold weather companion. Available in sixpacks and on draft from late October through January. ','Smuttynose Brewing Company','Portsmouth, New Hampshire'),
	(78,'Smuttynose Baltic Porter','8.70%',NULL,'Native to northern Europe, Baltic porters evolved from British porters once exported to the Russian hinterland. Unlike their British cousins, Baltic porters are often brewed as lagers, the tradition we\'ve followed. This beer is big, bold & smooth, with malty flavors reminiscent of coffee, dark fruit & raisins.','Smuttynose Brewing Company','Portsmouth, New Hampshire'),
	(79,'Smuttynose Farmhouse Ale','9.30%',NULL,'A homage to traditional European beers brewed for quenching the thirst of farm workers of \"Saisonaires.\" A unique Belgian Saison yeast is used to impart a mixture of spice, fruity and earthy notes along with a lip smacking palatability.','Smuttynose Brewing Company','Portsmouth, New Hampshire'),
	(80,'Voodoo White Magick of the Sun','6.00%',NULL,'White Magic at the Sun is our Voodoo-ized version of a white ale. This spicy wheat ale is perfect for that true craft beer individual that seeks out beers of flavor and integrity to the craft of beer. This ale is fantastic with foods of flavor, blackened catfish and the like. So step into the Magick of the Sun.','Voodoo Brewing Co.','Meadville, Pennsylvania'),
	(81,'Blue Moon Belgian White Ale','5.40%',NULL,'Brewed with oats for creaminess and spiced with the perfect combination of orange peel and coriander. An unfiltered wheat ale spiced in the Belgian tradition for an uncommonly smooth taste. Gold medalist (white beer) at 1995 World Beer Championships, silver medalist (white beer) at 1996 and 1997 World Beer Championships.','Coors Brewing Company (MillerCoors)','Golden, Colorado'),
	(82,'Blue Moon Harvest Moon Pumpkin Ale','5.77%',NULL,'This amber colored flavored ale is brewed only in the autumn and combines the flavor of vine ripened pumpkin pie flavor with traditional crystal malt.','Coors Brewing Company (MillerCoors)','Golden, Colorado'),
	(83,'Blue Moon Pale Moon','5.40%',NULL,'Pale Moon is a drinkable pale ale that has a distinctive hop aroma without the lingering aftertaste. This Belgian Style Pale Ale is brewed with European malts, Cascade hops, and a touch of hibiscus and orange peel. These ingredients create a rich copper colored ale with a flavor.','Coors Brewing Company (MillerCoors)','Golden, Colorado'),
	(84,'Shipyard Pumpkinhead Ale','5.10%',NULL,'Shipyard Pumpkinhead Ale is a crisp and refreshing wheat ale with delightful aromatics and subtle spiced flavor.','Shipyard Brewing Company','Portland, Maine'),
	(85,'Shipyard Prelude Ale','6.80%',NULL,'Prelude Special Ale is full-bodied in the true English Style. It\'s a rich and nutty ale with a hoppy finish and an inviting deep amber hue. Available November-December.','Shipyard Brewing Company','Portland, Maine'),
	(86,'Shipyard Summer Ale','5.10%',NULL,'(Used to be Sirius Summer Wheat Ale) A traditional America Wheat beer that is less assertive than its Bavarian counterparts. An inviting golden color, mellow malted wheat flavor and less hoppy characteristics are sure to please those looking a clean, cool taste sensation.','Shipyard Brewing Company','Portland, Maine'),
	(87,'Shipyard Blue Fin Stout','5.00%',NULL,'A classic Irish stout with a deep, almost black body and a creamy white head that is always pleasing to drink. Blue Fin Stout is brewed and bottles according to tradition with only premium, high quality ingredients.','Shipyard Brewing Company','Portland, Maine'),
	(88,'Shipyard Monkey Fist IPA','6.90%',NULL,'Shipyard Monkey Fist IPA is the genesis of a new generation of IPA. The traditional elements of classic English IPA have been redefined by American craft beer innovation. Like the image suggests, Monkey Fist is edgy, aggressive, and unique in style. This beer is brilliant copper in color and exploding with Warrior, Glacier, and Cascade hop character but able to maintain a beautiful balance. Monkey Fist holds up to the spiciest foods or is delicious savored just on its own.','Shipyard Brewing Company','Portland, Maine'),
	(89,'Shipyard Export Ale','5.10%',NULL,'The Shipyard Brewing Company\'s flagship beer, is a full bodied ale, with a hint of sweetness up front, a subtle and distinctive hope taste, and a very clean and traditional finish.','Shipyard Brewing Company','Portland, Maine'),
	(90,'Shipyard Smashed Blueberry','9.00%',NULL,'Smashed Blueberry is the newest beer in Shipyard Brewing Company\'s Pugsley\'s Signature Series line. This beer is a hybrid between a Porter and a Scotch Ale and has a rich mouth feel and a body of complex intensity. Upfront, there are distinct flavors of coffee and chocolate beautifully accentuated by the aroma of fresh blueberries. The finish features a delicate balance of sweet fruit and dry hops. This beer pairs well with glazed duck, ribs, barbeque, chocolate, and blueberry deserts.','Shipyard Brewing Company','Portland, Maine'),
	(91,'Shipyard Double Old Thumper Ale','11.20%',NULL,'Double Old Thumper is the big brother of the British Grand Champion beer Old Thumper Extra Special Ale, which was created in 1979 by veteran British brewer, Peter Austin, founder of the Ringwood Brewery in Hampshire, England, and brewed in the United States solely by Shipyard. Shipyard\'s Master Brewer Alan Pugsley trained at the Ringwood Brewery before moving to the United States 25 years ago. Double Old Thumper was created by Pugsley and has 11.2% alcohol by volume. \"Despite its strength, this beer is a great example of balance between malt and hops lending to a surprising drinkability,\" noted Pugsley. Double Old Thumper has a brilliant deep copper hue and spicy hop aroma with a complex malty finish featuring a dry Simcoe Hop bite. ','Shipyard Brewing Company','Portland, Maine'),
	(92,'Magic Hat #9','5.10%',NULL,'Apricot flavouring. A Beer Cloaked in Secrecy An ale whose mysterious and unusual palate will swirl across your tongue and ask more questions than it answers. A beer brewed clandestinely and given a name whose meaning is never revealed. Why #9? Why, indeed. A sort of dry, crisp, fruity, refreshing, not-quite pale ale. #9 is really impossible to describe because there?s never been anything else quite like it. Fermented with our 150 year old strain of top-fermenting English yeast.','Magic Hat Brewing Company','South Burlington, Vermont'),
	(93,'Magic Hat Elder Betty','5.50%',NULL,'A golden haze for a summer\'s daze. Elder Betty is a weiss-style ale with a bready malt flavor balanced by a touch of hops and complimented by the tart berry flavors of elderberry.','Magic Hat Brewing Company','South Burlington, Vermont'),
	(94,'Magic Hat Vinyl','5.10%',NULL,'Vinyl sails in on her shining wings as the spinning sun returns. She is the season-shifter, bursting from her cocoon to sing the ancient song of vernal yearning and to summon spring?s sweet green return. Her metamorphosis becomes our own. Her thirsts are shared by all. Drink in her mysterious elixir as the revolution blooms again.','Magic Hat Brewing Company','South Burlington, Vermont'),
	(95,'Magic Hat Howl','4.60%',NULL,'Born of dark and cold and snow in the marrow of the northeast\'s longest night, HOWL comes in on wailing winds with winter weary eyes burning holes in sunless shadows. In its darkened depths out inner voids are warmed.','Magic Hat Brewing Company','South Burlington, Vermont'),
	(96,'Magic Hat Blind Faith','6.20%',NULL,'Created to aid in deciphering the puzzles along life\'s road, and interpreting signs in the voyages of the spirit. Brewed in homage to the wisdom of visionaries everywhere who blaze paths into uncharted territories. Our take on an India Pale Ale (IPA.) A deep golden amber ale with a rich up front malty nose finishing with a big, hoppy bite. Dry hopped to finish with a big fresh hop flavor. Fermented with our 150 year old strain of top fermenting yeast.','Magic Hat Brewing Company','South Burlington, Vermont'),
	(97,'Magic Hat Hi.P.A.','6.70%',NULL,'Hi.P.A. is a medium bodied groove with a fresh and fruitful nose of tympanic temptation. It begins and ends with a big hop bite that is itself forever balanced on the brink by a steady rhythm of malt. Dry hopped for extra quenching in the face of heat and beat, it\'s an ideal accompaniment to chilling out, turning inward or sailing onward through the music of the night toward the dawn of the mind. It\'s the liquid way to say be here now lest you never come this way again.','Magic Hat Brewing Company','South Burlington, Vermont'),
	(98,'Magic Hat Demo','6.00%',NULL,'Demo is a deliciously dark lick of an India Pale Ale. It\'s medley of roasted malts and heady hops will have your senses dancing to the beat of a different IPA.','Magic Hat Brewing Company','South Burlington, Vermont'),
	(99,'Magic Hat Ravell','5.60%',NULL,'An enormous play in one significant act, Ravell was a porter brewed with whole vanilla beans, once available whenever young William and father John deem it so.','Magic Hat Brewing Company','South Burlington, Vermont'),
	(100,'Magic Hat Wacko','4.50%',NULL,'A beer with beet juice color. Wacko is the liquid song of summer: Crisp like the morning, cool like the evening and quenching all day long. Pop the top and set your summer loose. Wacko is a delicious summer beer with a big malty aroma, a subdued hop bite and a clean, slightly sweet finish.','Magic Hat Brewing Company','South Burlington, Vermont'),
	(101,'Magic Hat Circus Boy','4.50%',NULL,'The Hefeweizen unfiltered and unfettered, Circus Boy is a unique and refreshing American-style Hefeweizen. Is he a who? Or a what? Or perhaps some of both? Be amazed by the flavorful haze of this wonderful wheat beer.','Magic Hat Brewing Company','South Burlington, Vermont');

/*!40000 ALTER TABLE `Beers` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table Reviews
# ------------------------------------------------------------

DROP TABLE IF EXISTS `Reviews`;

CREATE TABLE `Reviews` (
  `reviews_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `review` text,
  `beer_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`reviews_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;



# Dump of table Users
# ------------------------------------------------------------

DROP TABLE IF EXISTS `Users`;

CREATE TABLE `Users` (
  `user_id` int(200) NOT NULL AUTO_INCREMENT,
  `fbUser_id` varchar(255) NOT NULL,
  `firstName` varchar(100) DEFAULT NULL,
  `lastName` varchar(100) DEFAULT NULL,
  `profilePic` text NOT NULL,
  `email` varchar(200) DEFAULT NULL,
  `password` varchar(30) DEFAULT NULL,
  `reviews_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;




/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
